[package]
name = "wl-screenrec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", default-features = false, features = ["std", "derive"] }
wayland-client = "0.30"
wayland-protocols = { version = "0.30", features = ["client", "unstable"] }
wayland-protocols-wlr = { version = "0.1", features = ["client"] }
ffmpeg-next = "6.0.0"
ctrlc = "3.2.4"
thiserror = "1.0.38"
drm-fourcc = "2.2.0"
human-size = "0.4.2"

