[package]
name = "wl-screenrec"
description = "High performance screen/audio recorder for wlroots"
license-file = "LICENSE"
homepage = "https://github.com/russelltg/wl-screenrec"
repository = "https://github.com/russelltg/wl-screenrec"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", default-features = false, features = [
    "std",
    "derive",
    "help",
    "color",
    "usage",
    "error-context",
    "suggestions",
] }
wayland-client = "0.31"
wayland-protocols = { version = "0.31", features = [
    "client",
    "unstable",
    "staging",
] }
wayland-protocols-wlr = { version = "0.2", features = ["client"] }

# ffmpeg-next does not support ffmpeg 6.1 yet, so grab from the 6.1 PR
ffmpeg-next = { git = "https://github.com/zmwangx/rust-ffmpeg", rev = "24ccb76c8c99d1dd53addb1d4056aed450138567" }
thiserror = "1.0.38"
drm-fourcc = "2.2.0"
human-size = "0.4.2"
signal-hook = "0.3.15"
anyhow = "1.0.71"
libc = "0.2.147"


[dev-dependencies]
nix = { version = "0.27.1", default-features = false, features = [
    "signal",
    "process",
] }
serde_json = "1.0.103"

[profile.release]
lto = "thin"

# seee above
[patch.crates-io]
ffmpeg-sys-next = { git = "https://github.com/AdrianEddy/rust-ffmpeg-sys", rev = "f58d6f20afa3859f8b3aa00b064a5336f641e63e" }
