name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install deps
      run: sudo add-apt-repository ppa:savoury1/ffmpeg5 && sudo apt-get update && sudo apt-get dist-upgrade && sudo apt-get install -y libavcodec-dev libavformat-dev libavdevice-dev libavutil-dev
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    #- name: Run tests
    #  run: cargo test --verbose
